
spring:
  app:
    jwtSecret: s3cr37
    jwtExpirationMs: 36000000
  datasource:
    url: jdbc:postgresql://ep-snowy-rice-a26vn28i.eu-central-1.aws.neon.tech/Warehouse?user=Warehouse_owner&password=vu6SbB9lAwox&sslmode=require
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  address: 192.168.56.1
  port: 8081